-- THIS DROPS THE DATABASE IF IT ALREADY EXISTS
DROP DATABASE burgers_db;

-- THIS CREATES THE burgers_db
CREATE DATABASE burgers_db;

-- THIS DEISGNATES THE burgers_db TO BE AFFECTED
USE burgers_db;

-- THIS CREATES A NEW TABLE NAMED burgers 
CREATE TABLE burgers (
id INT NOT NULL AUTO_INCREMENT,
burger_name VARCHAR(30) NOT NULL,
devoured BOOLEAN DEFAULT false,
PRIMARY KEY (id)
)

-- THIS DIPLAYS THE burgers TABLE
SELECT * FROM burgers;